name: CI (macOS)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        default: 'npu_hle'
        required: true
  push:
    paths:
    - '.github/workflows/**'
    - '3rdparty/**'
    - 'scripts/**'
    - 'src/**'
    - 'COPYING'
    - 'makefile'
  pull_request:
    paths:
    - '.github/workflows/**'
    - '3rdparty/**'
    - 'scripts/**'
    - 'src/**'
    - 'COPYING'
    - 'makefile'

permissions:
  contents: read

jobs:
  build-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
        ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}
    - name: Install dependencies
      run: brew install python3 sdl2
    - name: Build
      env:
        USE_LIBSDL: 1
        TOOLS: 1
      run: make -j2
    - name: Validate
      run: ./mame -validate
    - uses: actions/upload-artifact@main
      with:
        name: mame-macos-${{ github.sha }}
        path: |
          mame
          chdman
          unidasm
        if-no-files-found: error
